### ISSUE TITLE
Crestron macro files are password protected

### ISSUE THREAD

**Issue by evgolsh** [songzh96/homebridge-crestron-lts#2]
Hello,

What is the password for the macros?

**Comment by songzh96** [comment]
Yes, this is a partially open source project, if you want more control there is a fee.

**Comment by Pugy365** [comment]
I am willing to pay a fee for the module password, I want to re-compile for my crestron series 2 processor.

**Comment by bmagrogan** [comment]
> 

@Pugy365 you can't use these modules on a Crestron 2 Series processor, these use SIMPL#, which requires either a 3 Series or 4 Series processor. There is nothing you can do to make them work on a 2 Series processor.

**Comment by songzh96** [comment]
Hi
I just saw your email, I can compile it for you. what accessories do you need


Songzh
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songzh96/homebridge-crestron-lts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月30日(星期五) 晚上11:34
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [songzh96/homebridge-crestron-lts] Crestron macro files are password protected (Issue #2)





 
I am willing to pay a fee for the module password, I want to re-compile for my creation series 2 processor.
