### ISSUE TITLE
Door Module

### ISSUE THREAD

**Issue by jredbart** [songzh96/homebridge-crestron-lts#6]
Hi There,

I Have downloaded release 1.0.0 but there seem to be some SIMPL+ modules missing. Please can you sure the door module with me?

**Comment by songzh96** [comment]
Songzh
***@***.***



&nbsp;
Hi，I don't maintain this plugin very much now, you can try to implement it through node-red


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songzh96/homebridge-crestron-lts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 凌晨0:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[songzh96/homebridge-crestron-lts] Door Module (Issue #6)





 
Hi There,
 
I Have downloaded release 1.0.0 but there seem to be some SIMPL+ modules missing. Please can you sure the door module with me?
