### ISSUE TITLE
Missing modules?

### ISSUE THREAD

**Issue by DR7** [songzh96/homebridge-crestron-lts#8]
The file offered for download here does not contain all modules, such as the "Dimming" module and many others, can you please post a new download with all the missing modules?

Also, it seems I can only add ten lights, and I cannot edit the modules at all to add more. For instance, if I want to add 15 switches, I cannot because the modules are locked. 

If you no longer wish to maintain the code, can you please unlock the modules so others can expand on this and use more devices? I'm not sure if you sell a full-featured 3 series module package, but this isn't mentioned looking at the images with the download, it shows other modules, and you're actually configuring "DimLightBulb" but have not included the module?

Any help would be appreciated, I spent days making this work and finally have a couple of lights working but now I realize I can't even add the rest of the switches and also my dimmers, I have about 35 in total :-(

**Comment by rhegiel7** [comment]
i have the same issue modules inside the macro zip is not complete
