### ISSUE TITLE
Access to Module Source

### ISSUE THREAD

**Issue by Pugy365** [songzh96/homebridge-crestron-lts#9]
I would like to modify the module and re-complie for a Series 2 processor. 
But am unable to do so as the modules are password protected, anyway you can open these up so changes can be made? 

Thanks

**Comment by bmagrogan** [comment]
This is for 3 series and 4 series processors only, it uses SIMPL#

**Comment by Rmota1992** [comment]
You can grant access or tell me the password so that I can help with crestron. not all modules are available for download.

**Comment by fratrecca** [comment]
> You can grant access or tell me the password so that I can help with crestron. not all modules are available for download.

Can you shar the module password also for me? Thanks

**Comment by Hollako** [comment]
Hey mates, I am interested to contribute in the development of this module however the passwords of Simpl+ module avoid us to continue, or we should start from scratch? is possible to share with us the password, please?

Thanks and Regards,

**Comment by songzh96** [comment]
Hi Everyone, 1.1.0 is no password version
